SQUID/pothole/urls.py
"""/* Django Urls to map page */"""

from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
app_name='pothole'
from .views import *

urlpatterns=[

	url(r'^$',views.index,name="index"),
	url(r'^checkuser$',views.check),
	url(r'^login$', views.login_user,name='login'),
    url(r'^logout$',views.logout_user, name='logout'),
    url(r'^dashboard$',views.dashboard),
    url(r'^potholedetail$',views.pothole),
    url(r'^map$',views.map),
    url(r'^analytics$',views.line_chart,
        name='line_chart'),
    url(r'^line_chart/json/$', views.line_chart_json,
        name='line_chart_json'),
    url(r'^line_chart_ride/json/$', views.line_chart_json_ride,
        name='line_chart_json_ride'),
    url(r'^radar_chart/json/$', views.radar_chart_json,
        name='radar_chart_json'),
    url(r'^locations$',views.locations),
]
'''
{'template_name': 'pothole/success.html'}
'''

SQUID/squid/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('pothole.urls')),

]

SQUID/pothole/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class PolylineData(models.Model):
	filename = models.CharField(max_length=30, blank=True)
	score = models.DecimalField(max_digits=9, decimal_places=6)

	def __str__(self):
            return ('#' + str(self.id) + ' File: ' + str(self.filename) + ' - Score: ' + str(self.score))

class Pothole(models.Model):
	rpi_id=models.CharField(max_length=30, blank=True)
	timestamp = models.DateTimeField(default=datetime.now, blank=True)

	def __str__(self):
            return ('#' + str(self.id) + ' TS: ' + str(self.timestamp).split()[0])

class Location(models.Model):
	p_id=models.ForeignKey(Pothole, on_delete=models.CASCADE, null=True, blank=True)
	latitude=models.DecimalField(max_digits=9, decimal_places=6)
	longitude=models.DecimalField(max_digits=9, decimal_places=6)

	def __str__(self):
            return ('#' + str(self.p_id) + '-Lat: ' + str(self.latitude) + '-Lon: ' + str(self.longitude))

class Image(models.Model):
	p_id=models.ForeignKey(Pothole, on_delete=models.SET_NULL, null=True)
	#image=models.ImageField()
	
	def camera_sample():
		pass

	def __str__(self):
            return ('#' + str(self.p_id) + ' Image')

class Intensity(models.Model):
	p_id=models.ForeignKey(Pothole, on_delete=models.SET_NULL, null=True)
	breadth=models.FloatField(blank=True)
	depth=models.FloatField(blank=True)

	def __str__(self):
            return ('#' + str(self.p_id) + ' Dimensions')

class Accelerometer(models.Model):
	p_id=models.ForeignKey(Pothole, on_delete=models.SET_NULL, null=True)
	xaxis=models.FloatField(blank=True)
	yaxis=models.FloatField(blank=True)
	zaxis=models.FloatField(blank=True)

	def __str__(self):
            return ('#' + str(self.p_id) + ' accelerometer data')

SQUID/pothole/forms.py
from django.contrib.auth.models import User
from django import forms

'''class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)


	class Meta:
		model=User
		field="__all__"

'''

SQUID/pothole/views.py
'''Importing necessary modules from python and django library'''

from django.shortcuts import render
from django.conf import settings
from pothole import views
from .models import *
from django.shortcuts import redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth import views as auth_views
from django.views.generic import View
from django.http import HttpResponse
from statistics import mean
import csv
from array import *
import re
import os
import numpy as np
import math
import pylab
from random import randint
from django.views.generic import TemplateView
from chartjs.views.lines import BaseLineChartView

"""/* A function to store x,y,z values from the csv generated /*"""
def xyzValues():
	with open(os.path.join(settings.MEDIA_ROOT,"data1_0.csv"), 'r') as k:
		data = [d for d in list(csv.reader(k, delimiter=',')) if d != []]
		print(data[0][0])
		t = [float(data[i][0]) for i in range(len(data)) if data[i][0]!='']
		x = [float(data[i][1]) for i in range(len(data)) if data[i][1]!='']
		y = [float(data[i][2]) for i in range(len(data)) if data[i][2]!='']
		z = [float(data[i][3]) for i in range(len(data)) if data[i][3]!='']

		return [t,x,y,z]

"""/* Classes to implement visualization by django-chartjs*/"""
class LineChartJSONView(BaseLineChartView):
	def get_labels(self):
		t,x,y,z = xyzValues()
		return t

	def get_providers(self):
		return ["x-axis","y-axis","z-axis"]

	def get_data(self):
		t,x,y,z = xyzValues()
		return [x,y,z]

class LineChartJSONViewRide(BaseLineChartView):
	def get_labels(self):
		t,x,y,z = xyzValues()
		return t

	def get_providers(self):
		return ["Ride-Quality_Score"]
	def get_data(self):
		t,x,y,z = xyzValues()
		score=[]
		for i in range(len(x)):
			score.append(math.sqrt((x[i]**2 + y[i]**2 + z[i]**2)))
		return [score]

class RadarChartJSONViewRide(BaseLineChartView):
	def get_labels(self):
		return ["High","Medium","Low"]

	def get_providers(self):
		return ["High Count","Medium Count","Low Count"]
	def get_data(self):
		hc,mc,lc = [],[],[]
		for i in range(0,100,10):
			hc.append(i)
		for j in range(0,70,10):
			mc.append(j)
		for k in range(0,82,10):
			lc.append(i)
		# score = float(score)
		return [[76,0,0],[0,82,0],[0,0,63]]


'''/* Implementing visualization */'''
line_chart = TemplateView.as_view(template_name='pothole/analytics.html')
line_chart_json = LineChartJSONView.as_view()

line_chart_json_ride = LineChartJSONViewRide.as_view()

radar_chart_json = RadarChartJSONViewRide.as_view()

'''/* Function to validate login */'''
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                return redirect('/dashboard')
            else:
                return render(request, 'pothole/index.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'pothole/index.html', {'error_message': 'Invalid login'})
    return render(request, 'pothole/index.html')

'''/* Function to logout */'''
def logout_user(request):
    logout(request)
    return render(request, 'pothole/index.html')



'''/* Function to render dashboard */'''
def index(request):
 	return render(request,'pothole/index.html')

# Routes
# 1. Not logged in:
	# check if logged in: /check
	# if authenticated go to /dashboard
	# else /loginpage
def check(request):
	print("I m chcek")
	if request.session.has_key('username'):
		print("I m authenticated")
		return render(request,'pothole/dashboard.html')
	else:
		return render(request,'pothole/login.html')


def login(request):
	return render(request,'pothole/dashboard.html')


def logout(request):
    return render(request,'pothole/index.html')


'''/* Function to render dashboard */'''
def dashboard(request):
	return render(request,'pothole/dashboard.html')

'''/* Function to render analytics */'''
def analytics(request):
	return render(request,'pothole/analytics.html')

'''/* Function to  generate colorcode based on ride quality score */'''
def getcolorcode(score):
	if score >=8.381720005464272 and score <=8.63253751062201:
		color = '#003300'
	elif score >8.63253751062201 and score <=8.883355015779747:
		color = '#009900'
	elif score >8.883355015779747 and score <=9.134172520937485:
		color = '#00CC33'
	elif score >9.134172520937485 and score <=9.384990026095222:
		color = '#CC9900'
	elif score >9.384990026095222 and score <=9.63580753125296:
		color = '#CCCC00'
	elif score >9.63580753125296 and score <=9.886625036410697:
		color = '#CCFF00'
	elif score >9.886625036410697 and score <=10.137442541568435:
		color = '#880000'
	elif score >10.137442541568435 and score <=10.388260046726172:
		color = '#580000'
	else:
		color = '#380000'
	return color

'''/* Function to display ride quality on google maps */'''
def map(request):
    data = PolylineData.objects.all()

    os.chdir(settings.MEDIA_ROOT)
    locations = []
    for f in data:
        with open('{}\\'.format(settings.MEDIA_ROOT) + f.filename) as k:
            all_data = list(csv.reader(k , delimiter=','))

        i=0
        for m in range(0, len(all_data), 20):
            with open('{}\\'.format(settings.MEDIA_ROOT) + f.filename.rstrip('.csv') + '_{}.csv'.format(i), 'w+') as t:
                w = csv.writer(t, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                for row in all_data[m:m+21]:
                    w.writerow(row)
                i+=1

    f = [f for f in os.listdir(settings.MEDIA_ROOT) if re.search(r'.*_.*\.csv$',f)]

    for everyfile in f:
        with open(everyfile, 'r') as k:
            lis = []
            locationcol = {}
            data = [d for d in list(csv.reader(k , delimiter=',')) if d!=[]]
            print(data)
            print(mean([float(data[i][1]) for i in range(len(data)) if data[i][1]!='']))
            """/* Calculating mean of data to eliminate noise*/"""
            x = mean([float(data[i][1]) for i in range(len(data)) if data[i][1]!=''])
            y = mean([float(data[i][2]) for i in range(len(data)) if data[i][2]!=''])
            z = mean([float(data[i][3]) for i in range(len(data)) if data[i][3]!=''])

            #<!---Calculating ride quality score !--->
            score = math.sqrt((x**2 + y**2 + z**2))

            latitude = [float(data[i][4]) for i in range(len(data)) if data[i][4]!='']
            longitude = [float(data[i][5]) for i in range(len(data)) if data[i][5]!='']
   			"""Zipping the contents"""
            for lat,longi in zip(latitude, longitude):
                lis.append({"lat": lat, "lng": longi})

            locationcol['location'] = lis
            locationcol['color'] = getcolorcode(score)
            locations.append(locationcol)

    context = {
        'locations': locations
    }
    return render(request,'pothole/map.html', context)


"""/*Treshold algorithm to detect pothole*/"""
def thresholding_algo(y, lag, threshold, influence):
    signals = np.zeros(len(y))
    filteredY = np.array(y)
    avgFilter = [0]*len(y)
    stdFilter = [0]*len(y)
    avgFilter[lag - 1] = np.mean(y[0:lag])
    stdFilter[lag - 1] = np.std(y[0:lag])
    for i in range(lag, len(y) - 1):
        if abs(y[i] - avgFilter[i-1]) > threshold * stdFilter[i-1]:
            if y[i] > avgFilter[i-1]:
                signals[i] = 1
            else:
                signals[i] = -1

            filteredY[i] = influence * y[i] + (1 - influence) * filteredY[i-1]
            avgFilter[i] = np.mean(filteredY[(i-lag):i])
            stdFilter[i] = np.std(filteredY[(i-lag):i])
        else:
            signals[i] = 0
            filteredY[i] = y[i]
            avgFilter[i] = np.mean(filteredY[(i-lag):i])
            stdFilter[i] = np.std(filteredY[(i-lag):i])

    print(np.asarray(signals))
    return dict(signals = np.asarray(signals),
                avgFilter = np.asarray(avgFilter),
                stdFilter = np.asarray(stdFilter))


"""/* Pinpointing pothole locations */"""
def locations(request):
	locations=[]
	os.chdir(settings.MEDIA_ROOT)
	f = [f for f in os.listdir(settings.MEDIA_ROOT) if re.search(r'.*_.*\.csv$',f)]

	for everyfile in f[:5]:
		with open(everyfile, 'r') as k:
		    data = [d for d in list(csv.reader(k, delimiter=',')) if d != []]
		    lis=[]
		    locationcol = {}
		    lati_l = []
		    longi_l =[]
		    y = np.array([float(data[i][3]) for i in range(len(data)) if data[i][3]!=''])
		    lat = np.array([float(data[i][4]) for i in range(len(data)) if data[i][4]!=''])
		    lon = np.array([float(data[i][5]) for i in range(len(data)) if data[i][5]!=''])
		    # Settings: lag = 30, threshold = 5, influence = 0
		    lag = 2
		    threshold = 3
		    influence = 2

		    # Run algo with settings from above
		    result = thresholding_algo(y, lag=lag, threshold=threshold, influence=influence)

		    #map entries
		    for i in range(0,len(result["signals"])):
		    	if(result["signals"][i] == 1 or result["signals"][i] == -1):
		    		lati_l.insert(i,lat[i])
		    		longi_l.insert(i,lon[i])

		    for lat,longi in zip(lati_l, longi_l):
		    	lis.append({"lat": lat, "lng": longi})

		    locationcol['location'] = lis
		    locations.append(locationcol)
	context = {
        'locations': locations
    }
	return render(request,'pothole/locations.html',context)

SQUID/pothole/templates/pothole/analytics.html
{% extends 'pothole/base.html' %}
{% load staticfiles %}
{% block analytics %}active{% endblock %}
{% block content %}
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-lg-12 col-xl-12">
                        <!-- Basic map start -->
                        <div class="card">
                            <div class="card-header">
                                <h5>Basic</h5>
                                <span>Some visualization</span>

                                <div class="col-lg-12 col-xl-12">
                                    <canvas id="myChart"></canvas>
                                </div>
                                <br><hr><br>
                                <div class="col-lg-12 col-xl-12">
                                    <canvas id="myChartride"></canvas>
                                </div>
                                <br><hr><br>
                                <div class="col-lg-12 col-xl-12">
                                    <canvas id="myChartradar"></canvas>
                                </div>
                                

                                <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
                                <script type="text/javascript" src="{% static 'js/Chart.min.js' %}"></script>
                                <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
                                <script type="text/javascript">
                                    $.get('{% url 'pothole:line_chart_json' %}', function(data) {
                                        var ctx = $("#myChart").get(0).getContext("2d");
                                        data.datasets[0].backgroundColor = "rgba(0,0,0,0.8)"
                                        new Chart(ctx, {
                                            type: 'line', data: data
                                        });
                                    });
                                </script>
                                <script type="text/javascript">
                                    $.get('{% url 'pothole:line_chart_json_ride' %}', function(data) {
                                        var ctx = $("#myChartride").get(0).getContext("2d");
                                        data.datasets[0].backgroundColor = "rgba(0,0,100,0.678912345)"
                                        new Chart(ctx, {
                                            type: 'line', data: data
                                        });
                                    });
                                </script>

                                <script type="text/javascript">
                                    $.get('{% url 'pothole:radar_chart_json' %}', function(data) {
                                        var ctx = $("#myChartradar").get(0).getContext("2d");
                                        data.datasets[0].backgroundColor = "rgba(0,0,0,0.8)"
                                        new Chart(ctx, {
                                            type: 'bar', data: data
                                        });
                                    });
                                </script>
                            </div>
                        </div>
                        <!-- Basic map end -->
                    </div>

                </div>
            </div>
        </div>
        <!-- Main-body end -->
    </div>
</div>

{% endblock content %}   

SQUID/pothole/templates/pothole/dashboard.html
{% extends 'pothole/base.html' %}
{% load staticfiles %}
{% block dashboard %}active{% endblock %}
{% block content %}
<div class="pcoded-inner-content">
                <!-- Main-body start -->
                <div class="main-body">
                    <div class="page-wrapper">
                        <!-- Page-body start -->
                        <div class="page-body">
                            <div class="row">
                                <!--  project and team member start -->
                                <div class="col-xl-12 col-md-12">
                                    <div class="card table-card">
                                        <div class="card-header">
                                            <h5>Dashboard</h5>
                                            <div class="card-header-right">
                                                <ul class="list-unstyled card-option">
                                                    <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                                    <li><i class="fa fa-window-maximize full-card"></i></li>
                                                    <li><i class="fa fa-minus minimize-card"></i></li>
                                                    <li><i class="fa fa-refresh reload-card"></i></li>
                                                    <li><i class="fa fa-trash close-card"></i></li>
                                                </ul>
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div>
                                <!--  project and team member end -->
                            </div>
                        </div>
                        <!-- Page-body end -->
                    </div>
                    <div id="styleSelector"> </div>
                </div>
</div>
{% endblock content %}  

SQUID/pothole/templates/pothole/locations.html
{% extends 'pothole/base.html' %}
{% load staticfiles %}
{% block locations %}active{% endblock %}
{% block content %}
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-lg-12 col-xl-12">
                        <!-- Basic map start -->
                        <div class="card">
                            <div class="card-header">
                                <h5>Basic</h5>
                                <span>Map shows places around the world</span>
                            </div>
                            <div class="card-block">
                                <div id="map" class="set-map"></div>
                            </div>
                        </div>
                        <!-- Basic map end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Main-body end -->

        <div id="styleSelector">

        </div>
    </div>
 </div>
 <script>
   
     function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 30,
          center: {lat: 19.17377, lng: 72.95607},
          mapTypeId: 'terrain'
        });
       {% for item in locations%}
         var flightPlanCoordinates = {{ item.location|safe }};
         console.log(flightPlanCoordinates);
         var j;
         for(j=0;j<flightPlanCoordinates.length; j++){
          console.log(j)
          console.log(flightPlanCoordinates[j].lng);


          
          var infowindow = new google.maps.InfoWindow();
          var marker, i;

          // for (i = 0; i < flightPlanCoordinates[j].length; i++) {  

            marker = new google.maps.Marker({
              position: new google.maps.LatLng(flightPlanCoordinates[j].lat, flightPlanCoordinates[j].lng),
              map: map
            });
            google.maps.event.addListener(marker, 'click', (function(marker, j) {
                    return function() {
                      infowindow.setContent("pothole here");
                      infowindow.open(map, marker);
                    }
                  })(marker, j));
             // }    
         }
         
         
       {% endfor %}

       // console.log(locations)
     };
 
       
     </script>
     <script async defer
     src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqvGJptlGEn2obUoKnhGVkJp09rahvXlU&callback=initMap">
     </script>
{% endblock content %}   

SQUID/pothole/templates/pothole/map.html
{% extends 'pothole/base.html' %}
{% load staticfiles %}
{% block map %}active{% endblock %}
{% block content %}
<!-- Page-header end -->
<div class="pcoded-inner-content">
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page body start -->
            <div class="page-body">
                <div class="row">
                    <div class="col-lg-12 col-xl-12">
                        <!-- Basic map start -->
                        <div class="card">
                            <div class="card-header">
                                <h5>Basic</h5>
                                <span>Map shows places around the world</span>
                                
                            </div>
                            <div class="card-block">
                                <div id="map" class="set-map"></div>
                            </div>
                        </div>
                        <!-- Basic map end -->
                    </div>
                </div>
            </div>
        </div>
        <!-- Main-body end -->

        <div id="styleSelector">

        </div>
    </div>
 </div>
 <script>
   
     function initMap() {
       var map = new google.maps.Map(document.getElementById('map'), {
         zoom: 50,
         center: {lat: 19.18744, lng: 72.97267},
         mapTypeId: 'terrain'
       });
       {% for item in locations%}
         var flightPlanCoordinates = {{ item.location|safe }};
         
         var flightPath = new google.maps.Polyline({
           path: flightPlanCoordinates,
           geodesic: true,
           strokeColor: '{{ item.color }}',
           strokeOpacity: 1.0,
           strokeWeight: 8,
         });
         flightPath.setMap(map);
       {% endfor %}
     }
 
       
     </script>
     <script async defer
     src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqvGJptlGEn2obUoKnhGVkJp09rahvXlU&callback=initMap">
     </script>
{% endblock content %}   

SQUID/pothole/templates/pothole/pothole.html
{% extends 'pothole/base.html' %}
{% load staticfiles %}
{% block pothole %}active{% endblock %}
{% block content %}
<style>

.label-medium {
  vertical-align: super;
  font-size: small;
} 

.label-large {
  vertical-align: super;
  font-size: medium;
}

.label-bs {
  vertical-align: super;
}
</style>            
<div class="pcoded-inner-content">
    <!-- Main-body start -->
    <div class="main-body">
        <div class="page-wrapper">
            <!-- Page-body start -->
            <div class="page-body">
                <div class="row">
                    <!--  project and team member start -->
                    <div class="col-xl-12 col-md-12">
                        <div class="card table-card">
                            <div class="card-header">
                                <h5>Potholes nearby</h5>
                                <div class="card-header-right">
                                    <ul class="list-unstyled card-option">
                                        <li><i class="fa fa fa-wrench open-card-option"></i></li>
                                        <li><i class="fa fa-window-maximize full-card"></i></li>
                                        <li><i class="fa fa-minus minimize-card"></i></li>
                                        <li><i class="fa fa-refresh reload-card"></i></li>
                                        <li><i class="fa fa-trash close-card"></i></li>
                                    </ul>
                                </div>
                            </div>

                            <div class="card-block">
                                <div class="table-responsive">
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th>Pothole</th>
                                            <!-- <th>Lattitude</th> -->
                                            <!-- <th>Longitude</th> -->
                                            <th>Detected on</th>
                                            <th>Latitude</th>
                                            <th>Longitude</th>
                                            <th>Score</th>
                                            <!-- <th>Photographs</th> -->
                                            <th>Priority</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for j in final_data %}
                                        
                                        <tr>
                                            <td>
                                               <div class="d-inline-block align-middle">
                                                    
                                                    <div class="d-inline-block">
                                                        <h6>{{forloop.counter}}</h6>
                                                        <!-- <p class="text-muted m-b-0">Graphics Designer</p> -->
                                                    </div>
                                                </div>
                                            </td>
                                           <td>{{j.0}}</td>
                                            <td>{{j.1}}</td>
                                            <td>{{j.2}}</td>
                                            <td>{{j.3}}</td>
                                            <td>
                                                {% if j.4 == "High" %}    
                                                <label class="label label-danger label-medium" style="background-color:red;color: white;">{{j.4}}</label>
                                                {% elif j.4 == "Medium" %}
                                                <label class="label label-warning label-medium" style="background-color:yellow;color: white;">{{j.4}}</label>
                                                {% else %}
                                                <label class="label label-success label-medium" style="background-color:green;color: white;">{{j.4}}</label>
                                                {% endif %}
                                            </td>
                                        </tr>
                                        
                                        {% endfor %}

                                        
                                        
                                        </tbody>
                                    </table>
                                    <div class="text-right m-r-20">
                                        <a href="#!" class=" b-b-primary text-primary">View all Projects</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--  project and team member end -->
                </div>
            </div>
            <!-- Page-body end -->
        </div>
        <div id="styleSelector"> </div>
    </div>                
</div>
{% endblock content %}   

SQUID/pothole/templates/pothole/showmap.html
<!-- {{locations|safe}} -->
<!-- {% for item in locations %}
  {{ item|safe }};
{% endfor %} -->
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Simple Polylines</title>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <!-- {{locations|safe}} -->
    <div id="map"></div>
    <script>
      
        function initMap() {
          var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 25,
            center: {lat: 19.18744, lng: 72.97267},
            mapTypeId: 'terrain'
          });
          {% for item in locations%}
            var flightPlanCoordinates = {{ item.location|safe }};
            
            var flightPath = new google.maps.Polyline({
              path: flightPlanCoordinates,
              geodesic: true,
              strokeColor: '{{ item.color }}',
              strokeOpacity: 1.0,
              strokeWeight: 10,
            });
            flightPath.setMap(map);
          {% endfor %}
        }
    
          
        </script>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBqvGJptlGEn2obUoKnhGVkJp09rahvXlU&callback=initMap">
        </script>
  </body>
</html>